version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    groups:
      linters:
        patterns:
          - "ruff"
          - "isort"
          - "flake8*"
          - "wemake-python-styleguide"
          - "mypy"
      docs:
        patterns:
          - "sphinx*"
          - "shibuya"
          - "esbonio"
      tests:
        patterns:
          - "pytest*"
          - "pyfakefs"
          - "coverage"
    labels:
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
