version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    post_install:
      - python -m sphinx-build -b gettext . _build/gettext
      - python -m sphinx-intl update -p _build/gettext -l en

sphinx:
  configuration: docs/conf.py 

python:
  install:
    - requirements: docs/requirements.txt
