set windows-shell := ["powershell.exe", "-NoLogo", "-Command"]
set shell := ["bash", "-c"]

# Variables
sphinxopts := ""
sphinxbuild := "sphinx-build"
sourcedir := "."
builddir := "_build"

# Default recipe (help)
default:
    @{{sphinxbuild}} -M help "{{sourcedir}}" "{{builddir}}" {{sphinxopts}}

# Build the documentation
build:
    {{sphinxbuild}} -b html {{sourcedir}} {{builddir}}/html

# Live preview
live:
    sphinx-autobuild -b html . _build/html
